/** `aesop init` — detect → interview → build manifest → validate → write aesop.yaml.
 *  `aesop init --refresh` — re-run detection against an existing manifest and diff it. */
import { writeFile, access } from "node:fs/promises";
import { join } from "node:path";
import { detect, type Detection } from "../detect.js";
import { interview, defaults, type Answers, type InitOptions } from "../interview.js";
import { loadManifest, serializeManifest, validateManifest, AesopError } from "../manifest.js";
import type { InstructionBlock, Manifest } from "../types.js";

const TEST_PLACEHOLDER = "TODO: set your test command"; // honest placeholder; doctor flags it (Phase 4)

export function buildManifest(detection: Detection, answers: Answers): Manifest {
  const test = answers.testCommand ?? detection.commands.test ?? TEST_PLACEHOLDER;
  const blocks: InstructionBlock[] = detection.existingInstructionFiles.map((f) => ({
    scope: "project",
    content: `<!-- imported by aesop init from ${f.path}; review and fold into canonical blocks -->\n${f.content}`,
  }));

  return {
    version: 1,
    project: {
      name: detection.name,
      ...(detection.stack.length ? { stack: detection.stack } : {}),
      commands: {
        test,
        ...(detection.commands.build ? { build: detection.commands.build } : {}),
        ...(detection.commands.lint ? { lint: detection.commands.lint } : {}),
      },
      ...(detection.monorepo ? { monorepo: detection.monorepo } : {}),
      ...(answers.invariants.length ? { invariants: answers.invariants } : {}),
      ...(answers.models ? { models: answers.models } : {}),
      review_bandwidth: answers.review_bandwidth,
    },
    harnesses: answers.harnesses,
    pathway: { profile: answers.pathway },
    registries: ["builtin"],
    primitives: {
      instructions: {
        template: "builtin:AGENTS.template",
        ...(blocks.length ? { blocks } : {}),
      },
      skills: ["spec-first", "verify-loop", "lessons-loop"],
      agents: ["explorer", "verify-app"],
      commands: ["commit-pr", "fix-ci", "add-learning"],
      mcp: [], // thin by default (Boris); add when a workflow needs one
      hooks: ["format-on-write"],
      permissions: {
        mutate_allow: ["git commit *"],
        irreversible: ["git push origin main", "git push origin master"],
        unattended: "none",
      },
      loops: [],
    },
    state: { dir: "tasks/" },
  };
}

export interface InitResult {
  manifest: Manifest;
  path: string;
  detection: Detection;
}

export async function runInit(opts: InitOptions): Promise<InitResult> {
  const path = join(opts.cwd, "aesop.yaml");
  if (!opts.force) {
    try {
      await access(path);
      throw new AesopError(1, `aesop.yaml already exists at ${path} (use --force to overwrite, or edit it and run: aesop compile)`);
    } catch (e) {
      if (e instanceof AesopError) throw e;
      // ENOENT — good, proceed
    }
  }

  const detection = await detect(opts.cwd);
  const answers = opts.yes ? defaults(detection, opts) : await interview(detection, opts);
  const manifest = buildManifest(detection, answers);

  const { valid, errors } = validateManifest(manifest);
  if (!valid) {
    throw new AesopError(2, `generated manifest failed validation (this is a bug in aesop):\n  - ${errors.join("\n  - ")}`);
  }

  await writeFile(path, serializeManifest(manifest, `generated by \`aesop init\` on ${new Date().toISOString().slice(0, 10)}`), "utf8");
  return { manifest, path, detection };
}

export interface RefreshChange {
  field: string;
  current: string | undefined;
  detected: string;
}

export interface RefreshResult {
  changes: RefreshChange[];
  written: boolean;
}

/** Re-run detection and diff it against the manifest's *detected* fields only. Interviewed
 *  fields (invariants, models, review_bandwidth, harnesses, pathway) are the human's — never
 *  touched. Detection finding nothing is not evidence of removal: only a detected value that
 *  exists and differs is reported, so a hand-tuned command never disappears on refresh. */
export async function runRefresh(opts: { cwd: string; write?: boolean }): Promise<RefreshResult> {
  const manifest = await loadManifest(opts.cwd);
  const detection = await detect(opts.cwd);

  const changes: RefreshChange[] = [];
  for (const key of ["test", "build", "lint"] as const) {
    const detected = detection.commands[key];
    const current = manifest.project.commands[key];
    if (detected && detected !== current) changes.push({ field: `project.commands.${key}`, current, detected });
  }
  if (detection.stack.length && detection.stack.join(", ") !== (manifest.project.stack ?? []).join(", ")) {
    changes.push({ field: "project.stack", current: manifest.project.stack?.join(", "), detected: detection.stack.join(", ") });
  }
  const detectedPkgs = detection.monorepo?.packages.join(", ");
  if (detectedPkgs && detectedPkgs !== manifest.project.monorepo?.packages.join(", ")) {
    changes.push({ field: "project.monorepo.packages", current: manifest.project.monorepo?.packages.join(", "), detected: detectedPkgs });
  }

  if (!opts.write || !changes.length) return { changes, written: false };

  for (const key of ["test", "build", "lint"] as const) {
    if (detection.commands[key]) manifest.project.commands[key] = detection.commands[key];
  }
  if (detection.stack.length) manifest.project.stack = detection.stack;
  if (detection.monorepo) manifest.project.monorepo = detection.monorepo;

  const { valid, errors } = validateManifest(manifest);
  if (!valid) {
    throw new AesopError(2, `refreshed manifest failed validation (this is a bug in aesop):\n  - ${errors.join("\n  - ")}`);
  }
  await writeFile(join(opts.cwd, "aesop.yaml"), serializeManifest(manifest, "updated by `aesop init --refresh --write`"), "utf8");
  return { changes, written: true };
}

export function refreshSummary(result: RefreshResult): string {
  if (!result.changes.length) return "fresh: detection matches the manifest.";
  const rows = result.changes.map((c) => `  ${c.field}\n    manifest: ${c.current ?? "(unset)"}\n    detected: ${c.detected}`);
  return [
    `detection drift in ${result.changes.length} field(s):`,
    ...rows,
    "",
    result.written ? "applied to aesop.yaml — review the diff, then run `aesop compile`." : "run `aesop init --refresh --write` to apply (interviewed fields are never touched).",
  ].join("\n");
}

export function initSummary(result: InitResult): string {
  const { manifest, detection, path } = result;
  const lines = [
    `Wrote ${path}`,
    ``,
    `  project    ${manifest.project.name}${manifest.project.stack ? `  (${manifest.project.stack.join(", ")})` : ""}`,
    `  test       ${manifest.project.commands.test}${manifest.project.commands.test === TEST_PLACEHOLDER ? "   ← set this; the verify loop is load-bearing" : ""}`,
    ...(manifest.project.commands.build ? [`  build      ${manifest.project.commands.build}`] : []),
    ...(manifest.project.commands.lint ? [`  lint       ${manifest.project.commands.lint}`] : []),
    ...(manifest.project.monorepo ? [`  monorepo   ${manifest.project.monorepo.packages.join(", ")}`] : []),
    `  harnesses  ${manifest.harnesses.join(", ")}`,
    `  pathway    ${manifest.pathway.profile}`,
    ...(detection.existingInstructionFiles.length
      ? [`  imported   ${detection.existingInstructionFiles.map((f) => f.path).join(", ")} (preserved as instruction blocks)`]
      : []),
    ``,
    `Next: review aesop.yaml, then run \`aesop compile\`.`,
    ``,
    `Three problems no loop solves for you:`,
    `  1. Verification is still yours — a loop running unattended is making mistakes unattended.`,
    `  2. Comprehension debt — read what the loop made, or the gap compounds.`,
    `  3. Cognitive surrender — design the loop with judgement, not to avoid thinking.`,
  ];
  return lines.join("\n");
}
