/** `aesop init` — detect → interview → build manifest → validate → write aesop.yaml. */
import { writeFile, access } from "node:fs/promises";
import { join } from "node:path";
import { detect, type Detection } from "../detect.js";
import { interview, defaults, type Answers, type InitOptions } from "../interview.js";
import { serializeManifest, validateManifest, AesopError } from "../manifest.js";
import type { InstructionBlock, Manifest } from "../types.js";

const TEST_PLACEHOLDER = "TODO: set your test command"; // honest placeholder; doctor flags it (Phase 4)

export function buildManifest(detection: Detection, answers: Answers): Manifest {
  const test = answers.testCommand ?? detection.commands.test ?? TEST_PLACEHOLDER;
  const blocks: InstructionBlock[] = detection.existingInstructionFiles.map((f) => ({
    scope: "project",
    content: `<!-- imported by aesop init from ${f.path}; review and fold into canonical blocks -->\n${f.content}`,
  }));

  return {
    version: 1,
    project: {
      name: detection.name,
      ...(detection.stack.length ? { stack: detection.stack } : {}),
      commands: {
        test,
        ...(detection.commands.build ? { build: detection.commands.build } : {}),
        ...(detection.commands.lint ? { lint: detection.commands.lint } : {}),
      },
      ...(detection.monorepo ? { monorepo: detection.monorepo } : {}),
      ...(answers.invariants.length ? { invariants: answers.invariants } : {}),
      ...(answers.models ? { models: answers.models } : {}),
      review_bandwidth: answers.review_bandwidth,
    },
    harnesses: answers.harnesses,
    pathway: { profile: answers.pathway },
    registries: ["builtin"],
    primitives: {
      instructions: {
        template: "builtin:AGENTS.template",
        ...(blocks.length ? { blocks } : {}),
      },
      skills: ["spec-first", "verify-loop", "lessons-loop"],
      agents: ["explorer", "verify-app"],
      commands: ["commit-pr", "fix-ci", "add-learning"],
      mcp: [], // thin by default (Boris); add when a workflow needs one
      hooks: ["format-on-write"],
      permissions: {
        mutate_allow: ["git commit *"],
        irreversible: ["git push origin main", "git push origin master"],
        unattended: "none",
      },
      loops: [],
    },
    state: { dir: "tasks/" },
  };
}

export interface InitResult {
  manifest: Manifest;
  path: string;
  detection: Detection;
}

export async function runInit(opts: InitOptions): Promise<InitResult> {
  const path = join(opts.cwd, "aesop.yaml");
  if (!opts.force) {
    try {
      await access(path);
      throw new AesopError(1, `aesop.yaml already exists at ${path} (use --force to overwrite, or edit it and run: aesop compile)`);
    } catch (e) {
      if (e instanceof AesopError) throw e;
      // ENOENT — good, proceed
    }
  }

  const detection = await detect(opts.cwd);
  const answers = opts.yes ? defaults(detection, opts) : await interview(detection, opts);
  const manifest = buildManifest(detection, answers);

  const { valid, errors } = validateManifest(manifest);
  if (!valid) {
    throw new AesopError(2, `generated manifest failed validation (this is a bug in aesop):\n  - ${errors.join("\n  - ")}`);
  }

  await writeFile(path, serializeManifest(manifest, `generated by \`aesop init\` on ${new Date().toISOString().slice(0, 10)}`), "utf8");
  return { manifest, path, detection };
}

export function initSummary(result: InitResult): string {
  const { manifest, detection, path } = result;
  const lines = [
    `Wrote ${path}`,
    ``,
    `  project    ${manifest.project.name}${manifest.project.stack ? `  (${manifest.project.stack.join(", ")})` : ""}`,
    `  test       ${manifest.project.commands.test}${manifest.project.commands.test === TEST_PLACEHOLDER ? "   ← set this; the verify loop is load-bearing" : ""}`,
    ...(manifest.project.commands.build ? [`  build      ${manifest.project.commands.build}`] : []),
    ...(manifest.project.commands.lint ? [`  lint       ${manifest.project.commands.lint}`] : []),
    ...(manifest.project.monorepo ? [`  monorepo   ${manifest.project.monorepo.packages.join(", ")}`] : []),
    `  harnesses  ${manifest.harnesses.join(", ")}`,
    `  pathway    ${manifest.pathway.profile}`,
    ...(detection.existingInstructionFiles.length
      ? [`  imported   ${detection.existingInstructionFiles.map((f) => f.path).join(", ")} (preserved as instruction blocks)`]
      : []),
    ``,
    `Next: review aesop.yaml, then run \`aesop compile\`.`,
    ``,
    `Three problems no loop solves for you:`,
    `  1. Verification is still yours — a loop running unattended is making mistakes unattended.`,
    `  2. Comprehension debt — read what the loop made, or the gap compounds.`,
    `  3. Cognitive surrender — design the loop with judgement, not to avoid thinking.`,
  ];
  return lines.join("\n");
}
